export const ManagerConstants = {
    CREATE_REQUEST: 'CREATE_REQUEST',
    CREATE_SUCCESS: 'CREATE_SUCCESS',
    CREATE_FAILURE: 'CREATE_FAILURE',
    CREATE_ACCOUNT_EXIST: 'CREATE_ACCOUNT_EXIST',

    READ_REQUEST: 'READ_REQUEST',
    READ_SUCCESS: 'READ_SUCCESS',
    READ_FAILURE: 'READ_FAILURE',
    READ_PERMISSION_DENY: 'READ_PERMISSION_DENY',

    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_FAILURE',
    UPDATE_PERMISSION_DENY: 'UPDATE_PERMISSION_DENY',

    DELETE_REQUEST: 'DELETE_REQUEST',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELITE_FAILURE: 'DELETE_FAILURE',
    DELITE_PERMISSION_DENY: 'DELETE_PERMISSION_DENY',
    
}