export const ManagerConstants = {
    CREATE_REQUEST: 'CREATE_REQUEST',
    CREATE_SUCCESS: 'CREATE_SUCCESS',
    CREATE_FAILURE: 'CREATE_FAILURE',
    CREATE_ACCOUNT_EXIST: 'CREATE_ACCOUNT_EXIST',

    READ_REQUEST: 'READ_REQUEST',
    READ_SUCCESS: 'READ_SUCCESS',
    READ_FAILURE: 'READ_FAILURE',
    READ_PERMISSION_DENY: 'READ_PERMISSION_DENY',

    _REQUEST: '_REQUEST',
    _SUCCESS: '_SUCCESS',
    _FAILURE: '_FAILURE',
    _ACCOUNT_EXIST: '_',
    
}